### ISSUE TITLE
Unable to duplicate rows due to FirstDisplayedScrollingRowIndex property cannot be set to an invisible row

### ISSUE THREAD

**Issue by khaledadrani** [vawser/Yapped-Rune-Bear#77]
At first, I installed Yapped. Everything was working fine. I created a new spell and it was added to Magic param with no error message. Next session tried to make another new spell and to create a new good out of the existing spell. An error occurs: 

************** Exception Text **************
System.InvalidOperationException: FirstDisplayedScrollingRowIndex property cannot be set to an invisible row.
   at System.Windows.Forms.DataGridView.set_FirstDisplayedScrollingRowIndex(Int32 value)
   at Chomp.Main.DuplicateRowToolStripMenuItem_Click(Object sender, EventArgs e) in E:\Program Files (x86)\SteamLibrary\steamapps\common\DARK SOULS III\Modding\Mods\Cinders\Tools\C# Projects\Yapped-Rune-Bear\Forms\Main.cs:line 868
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam) 

Any idea why does this happen? And how to fix it? In fact, why is it calling Main.cs from Cinders Mod in disk E which I don't have in my system?

**Comment by khaledadrani** [comment]
It happens when you try to give it an existing id that you made invisible with the search function "Apply". Don't use Apply if you plan to duplicate rows.
